### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Carlomos7** [bentzi-shuster/MoniesPlaner#11]
- [ ] Plan the test scenarios for each user story based on their acceptance criteria and requirements.
- [ ] Write Playwright tests for each user story to verify the functionality and behavior of the application.
- [ ] Automate the Playwright tests to allow for continuous integration and regression testing.
- [ ] Execute the Playwright tests regularly to catch potential regressions or defects.
- [ ] Record test results and report any issues or bugs found during testing.
- [ ] Keep the tests up to date with changes in the application and codebase.
- [ ] Add new tests for new features or user stories as they are implemented.

**Comment by bentzi-shuster** [comment]
[component-testing branch](https://github.com/bentzi-shuster/MoniesPlaner/tree/component-testing)
